<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{89dc724e-e8f7-4f0a-8ccf-d584989e3263}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN 
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SavePersistentVariables ();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>